# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0bf0308e83e49afbdf23817c4bf67b50eb5fe371871f8abfb96f47ce7e270dc04caacb8d8dd2b2b0f5e34e31f96d1a22827040c5143f21145a9b442be0c5f98

test:
  secret_key_base: a1841a065e7f96e5f8b7ad7df7fcfc0c96e8815f0a6f8015df51663ed08f9feb0bc7b8371f2c6f3bee1f2a75a98e54db2e0755fc73b743d7d95c4d5062e5c886

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
